// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcyPWXC-LVGwZNrvugODChoRndv7Jvto',
    appId: '1:517227415529:web:91c73678fa973040c12d78',
    messagingSenderId: '517227415529',
    projectId: 'flutterchatapp-38699',
    authDomain: 'flutterchatapp-38699.firebaseapp.com',
    storageBucket: 'flutterchatapp-38699.appspot.com',
    measurementId: 'G-VHXXMFK5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Yroz60wZ6mS2Gwoh7qQFjmdaBk7Inb0',
    appId: '1:517227415529:android:32c342a600c07e63c12d78',
    messagingSenderId: '517227415529',
    projectId: 'flutterchatapp-38699',
    storageBucket: 'flutterchatapp-38699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTZ4FvLfV_7NjLQpO9Ax7vgYTZVlX--A',
    appId: '1:517227415529:ios:28f01a288f0a6f7ac12d78',
    messagingSenderId: '517227415529',
    projectId: 'flutterchatapp-38699',
    storageBucket: 'flutterchatapp-38699.appspot.com',
    iosClientId: '517227415529-ecmnhjchteqttpugcobhr7e9csci1ecm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTZ4FvLfV_7NjLQpO9Ax7vgYTZVlX--A',
    appId: '1:517227415529:ios:28f01a288f0a6f7ac12d78',
    messagingSenderId: '517227415529',
    projectId: 'flutterchatapp-38699',
    storageBucket: 'flutterchatapp-38699.appspot.com',
    iosClientId: '517227415529-ecmnhjchteqttpugcobhr7e9csci1ecm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
